screen_size = { height = 20 } # use "fullscreen" to run pik in fullscreen

# [ignore]
# paths = []
# other_users = true
# threads = true

### UI Configuration ###
[ui]
# use_icons = true
icons = "nerd_font_v3"
