require("jkurlit.options")
require("jkurlit.keymaps")
require("jkurlit.colorscheme")
require("jkurlit.packer")
-- some colorschemes must be initialized before plugins (like nighfox to setup lualine correctly)
require("jkurlit.plugins")
