
theme = "spacebones_light"

[editor]
line-number = "relative"
idle-timeout = 200
completion-trigger-len = 1
indent-guides.render = false
cursorline = true
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name"]
right = ["selections", "position","position-percentage", "file-encoding", "file-type"]
separator = "│"